stages:
  data_sampling:
    cmd: python src/data_preprocessing/data_sampling.py
    deps:
      - src/data_preprocessing/data_sampling.py
      - src/data_preprocessing/data_preprocessing_utils.py
      - data/malicious_urls.csv
    outs:
      - data/malicious_urls_sampled.csv:
          cache: false
  data_preprocessing:
    cmd: python src/data_preprocessing/data_preprocessing.py
    deps:
      - src/data_preprocessing/data_preprocessing.py
      - src/data_preprocessing/data_preprocessing_utils.py
      - data/malicious_urls_sampled.csv
    outs:
      - data/urls_with_features.csv:
          cache: false
  
